USE freedb_MacroTrack;

CREATE TABLE Users (
    UserID INT AUTO_INCREMENT PRIMARY KEY,
    Email VARCHAR(255) NOT NULL UNIQUE,
    Username VARCHAR(50) NOT NULL UNIQUE,
    PasswordHash VARCHAR(255) NOT NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE UserTokens (
    TokenID INT AUTO_INCREMENT PRIMARY KEY,
    UserID INT NOT NULL,
    Token VARCHAR(255) NOT NULL UNIQUE,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (UserID) REFERENCES Users(UserID)
);

CREATE TABLE Food (
    FoodID INT AUTO_INCREMENT PRIMARY KEY,
    UserID INT NOT NULL,
    Name VARCHAR(50) NOT NULL,
    Proteins INT NOT NULL,
    Carbs INT NOT NULL,
    Fats INT NOT NULL,
    Calories INT GENERATED ALWAYS AS (Proteins * 4 + Carbs * 4 + Fats * 9) STORED,
    FOREIGN KEY (UserID) REFERENCES Users(UserID)
);

CREATE TABLE Logs (
    LogID INT AUTO_INCREMENT PRIMARY KEY,
    UserID INT NOT NULL,
    Date DATE NOT NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (UserID) REFERENCES Users(UserID)
);

CREATE TABLE LogFood (
    LogFoodID INT AUTO_INCREMENT PRIMARY KEY,
    LogID INT NOT NULL,
    FoodID INT NOT NULL,
    Quantity INT NOT NULL,
    FOREIGN KEY (LogID) REFERENCES Logs(LogID),
    FOREIGN KEY (FoodID) REFERENCES Food(FoodID)
);